name: HiTE
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
  - pytorch
dependencies:
  - python=3.9
  - java-jdk
  - pytorch
  - cpuonly
  - gxx=14.2.0
  - tensorflow=2.12.1
  - numpy=1.24.4
  - pandas=2.2.2
  - pysam
  - biopython
  - scikit-learn
  - seaborn
  - matplotlib
  - openpyxl
  - rmblast=2.14.0
  - repeatmasker=4.1.1
  - repeatmodeler=2.0.1=pl526_0
  - bedtools
  - cd-hit
  - samtools
  - fuzzysearch
  - mafft
  - ninja-nj
  - emboss
  - r-base=4.2.3
  - hisat2
  - trimmomatic
  - gffread
  - pygtftk
  - bioconductor-rsubread
  - r-mass
  - tqdm
  - pip
  - minimap2
  - pip:
    - python-Levenshtein
    - PyPDF2
    - PyMuPDF
    - statannot
    - psutil
    - intervaltree